### PR TITLE
prepare for python 3

### PR DESCRIPTION
**Pull request by jbleyel**
fix mixing tab and spaces
fix print
fix except

### CODE REVIEW

**Comment by fs-plugins** [comment]
very good !

**Comment by fs-plugins** [comment]
>>@jbleyel
[fix crash if PIL not installed]
how could the users use it for so many years on so many images, when it only consists of error and crash?

**Comment by fs-plugins** [comment]
@jbleyel
>>[more fixes]  ...[fix crash]...

yes, a python2 plugin will probably crash under python3
yes, many places in the plugin will not run under py3

but they are not fixes, but adaptations for Py3!
the plugins run in the original on many py2 images without crash!

so please stay objective
after all these years there is no adequate plugin for this purpose, and I make my code freely available here...
thanks

**Comment by jbleyel** [comment]
You do not need to merge all the changes to your repro.
The changes should also run on python 2.

**Comment by jbleyel** [comment]
> @jbleyel
> [fix crash if PIL not installed]
> how could the users use it for so many years on so many images, when it only consists of error and crash?

You probably use a very old version of PIL.
But your code will crash if PIL is not installed.

**Comment by jbleyel** [comment]
You can also close this PR and pick only the needed changes from the fork if you like.
I will not refactor the code, because I have no time to do this.

**Comment by fs-plugins** [comment]
>>I will not refactor the code, because I have no time to do this.
yes
Development, maintenance and adjustments require a lot of time and effort

**Pull request closed without merging**
